---
version: 0.1
runson: ${matrix.os}

runtime: 
  language: node
  version: 24

cypress: true
cypressOps:
  Build: "Hyperexecute Cypress Sample Build"
  Tags: ["HYP-Cypress", "Linux", "Matrix", "Accessibility"]
  BuildTags: ["HYP-Cypress-v15"]

pre:
  - npm install
  - npm install cypress --save-dev
  - npm i lambdatest-cypress-cli

matrix:
  os: [linux]
  browser: ["chrome"]
  files: ["actions.cy.js", "aliasing.cy.js", "assertions.cy.js", "connectors.cy.js", "cookies.cy.js"]

parallelism: 1

testSuites: 
  - npx cypress run --spec ./cypress/e2e/2-advanced-examples/$files --browser=$browser --headed --config video=true

jobLabel: [cypress-v15, linux, matrix]